// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for AI-powered content moderation.
 *
 * The flow takes user-generated text as input and uses an LLM to determine if it violates community guidelines.
 * It returns a boolean indicating whether the content is flagged for review.
 *
 * @exports {
 *   aiContentModeration,
 *   AiContentModerationInput,
 *   AiContentModerationOutput,
 * }
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Input schema for the aiContentModeration flow.
 */
const AiContentModerationInputSchema = z.object({
  text: z.string().describe('The user-generated text to be moderated.'),
});

/**
 * Type definition for the input to the aiContentModeration flow.
 */
export type AiContentModerationInput = z.infer<typeof AiContentModerationInputSchema>;

/**
 * Output schema for the aiContentModeration flow.
 */
const AiContentModerationOutputSchema = z.object({
  flagForReview: z.boolean().describe('Whether the content should be flagged for review.'),
  reason: z.string().optional().describe('The reason the content was flagged for review.'),
});

/**
 * Type definition for the output of the aiContentModeration flow.
 */
export type AiContentModerationOutput = z.infer<typeof AiContentModerationOutputSchema>;

/**
 * aiContentModeration flow.
 *
 * @param {AiContentModerationInput} input - The input to the flow.
 * @returns {Promise<AiContentModerationOutput>} - The output of the flow.
 */
export async function aiContentModeration(input: AiContentModerationInput): Promise<AiContentModerationOutput> {
  return aiContentModerationFlow(input);
}

const aiContentModerationPrompt = ai.definePrompt({
  name: 'aiContentModerationPrompt',
  input: {schema: AiContentModerationInputSchema},
  output: {schema: AiContentModerationOutputSchema},
  prompt: `You are a content moderation AI.  Your job is to read user-generated text and determine if it violates community guidelines.

  Here are the community guidelines:
  - Be respectful of others.
  - Do not post hate speech.
  - Do not post illegal content.
  - Do not post spam.

  Given the following text:
  {{text}}

  Determine if it violates community guidelines. Return 'true' for 'flagForReview' if it does, and 'false' if it doesn't.  If you flag the content for review, provide a brief reason.
  `,
});

const aiContentModerationFlow = ai.defineFlow(
  {
    name: 'aiContentModerationFlow',
    inputSchema: AiContentModerationInputSchema,
    outputSchema: AiContentModerationOutputSchema,
  },
  async input => {
    const {output} = await aiContentModerationPrompt(input);
    return output!;
  }
);
